# Generated by Django 5.2.7 on 2025-11-11 13:28

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to=account.models.user_resume_path),
        ),
    ]
